Email summary content lead
SERTwitter/ser pull request #15
Opened 2020-11-22 03:36 UTC by jrgant

I added a new exported function called `get_content_lead()` to retrieve the current content lead's email based on the current day. The function adds to the `send_summary_to` vector in `inst/email_summary.R`.

2020-11-22 03:38 UTC, jrgant commented
@malcolmbarrett This contains all the changes reflected in my prior pull request. Apologies, as I thought this new branch I created would only contain the changes I made related to the updated email summaries.

Let me know if you need me to do anything differently, since the other pull request (for the tweet library processing) should be handled first.

2021-04-14 23:41 UTC, malcolmbarrett commented
In future PRs, use `usethis::pr_init()`, which will prevent that problem

2021-04-14 23:47 UTC, malcolmbarrett requested changes
Outside of the comment I left, this looks good. You have your work cut out for you managing this merge, though, not working from a clean branch. You may be better off rebasing after merging #10

2021-04-14 23:47 UTC, malcolmbarrett commented on R/email_summary.R
> +  require(lubridate)
You should never use `library()` or `require()` in R package code.

Instead, if you need to call functions without pkg::, use `@importFrom`. Here, you need to add this to the roxygen: `@importFrom lubridate today %within% interval mdy`. 

However, my preference here is that you limit the import to `importFrom lubridate %within%` and use `lubridate::` for the rest.

2021-04-16 02:30 UTC, malcolmbarrett commented
Closing this in favor of #17 rather than doing git fu to get out of this merge situation

2021-04-16 02:30 UTC, closed without merging